# Generated by Django 3.0.5 on 2020-04-29 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200429_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', related_query_name='users', to='account.Room'),
        ),
    ]
