# Generated by Django 3.0.5 on 2020-04-29 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200429_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_room', related_query_name='my_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
